apiVersion: v1
kind: Service
metadata: 
  name: task-management
spec:
  type: LoadBalancer
  selector: 
    app: task-management
    tier: task-management
  ports: 
    - protocol: TCP
      port: 3000
      targetPort: 3000
